#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v18
# autospec commit: f35655a
#
# Source0 file verified with key 0x2C8DF587A6D4AAC1 (nicolas.fella@kde.org)
#
Name     : kholidays
Version  : 6.5.0
Release  : 87
URL      : https://download.kde.org/stable/frameworks/6.5/kholidays-6.5.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/6.5/kholidays-6.5.0.tar.xz
Source1  : https://download.kde.org/stable/frameworks/6.5/kholidays-6.5.0.tar.xz.sig
Source2  : 2C8DF587A6D4AAC1.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause CC0-1.0 GPL-3.0 LGPL-2.0
Requires: kholidays-data = %{version}-%{release}
Requires: kholidays-lib = %{version}-%{release}
Requires: kholidays-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
To generate the Bison/Flex parser/scanner code after any changes to
holidayparserplan.ypp or holidayscannerplan.lpp run:

%package data
Summary: data components for the kholidays package.
Group: Data

%description data
data components for the kholidays package.


%package dev
Summary: dev components for the kholidays package.
Group: Development
Requires: kholidays-lib = %{version}-%{release}
Requires: kholidays-data = %{version}-%{release}
Provides: kholidays-devel = %{version}-%{release}
Requires: kholidays = %{version}-%{release}

%description dev
dev components for the kholidays package.


%package lib
Summary: lib components for the kholidays package.
Group: Libraries
Requires: kholidays-data = %{version}-%{release}
Requires: kholidays-license = %{version}-%{release}

%description lib
lib components for the kholidays package.


%package license
Summary: license components for the kholidays package.
Group: Default

%description license
license components for the kholidays package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 2C8DF587A6D4AAC1' gpg.status
%setup -q -n kholidays-6.5.0
cd %{_builddir}/kholidays-6.5.0
pushd ..
cp -a kholidays-6.5.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1723240379
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1723240379
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kholidays
cp %{_builddir}/kholidays-%{version}/LICENSES/BSD-2-Clause.txt %{buildroot}/usr/share/package-licenses/kholidays/680ed9349d3d12bd39ddd36e8c4bc6b1b0cb1c0e || :
cp %{_builddir}/kholidays-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/kholidays/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/kholidays-%{version}/LICENSES/GPL-3.0-or-later.txt %{buildroot}/usr/share/package-licenses/kholidays/6091db0aead0d90182b93d3c0d09ba93d188f907 || :
cp %{_builddir}/kholidays-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kholidays/20079e8f79713dce80ab09774505773c926afa2a || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/locale/ar/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/ast/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/az/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/be/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/bg/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/br/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/bs/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/ca/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/ca@valencia/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/cs/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/cy/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/da/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/de/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/el/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/en_GB/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/eo/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/es/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/et/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/eu/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/fa/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/fi/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/fr/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/fy/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/ga/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/gl/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/he/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/hi/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/hne/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/hu/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/ia/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/id/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/is/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/it/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/ja/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/ka/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/kk/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/km/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/ko/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/lt/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/lv/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/mk/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/ml/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/mr/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/ms/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/nb/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/nds/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/ne/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/nl/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/nn/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/pa/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/pl/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/pt/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/pt_BR/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/ro/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/ru/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/se/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/sk/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/sl/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/sq/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/sr/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/sr@ijekavian/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/sr@ijekavianlatin/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/sr@latin/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/sv/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/ta/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/tg/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/th/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/tr/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/ug/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/uk/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/uz/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/uz@cyrillic/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/wa/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/zh_CN/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/locale/zh_TW/LC_MESSAGES/libkholidays6_qt.qm
/usr/share/qlogging-categories6/kholidays.categories

%files dev
%defattr(-,root,root,-)
/usr/include/KF6/KHolidays/KHolidays/AstroSeasons
/usr/include/KF6/KHolidays/KHolidays/Holiday
/usr/include/KF6/KHolidays/KHolidays/HolidayRegion
/usr/include/KF6/KHolidays/KHolidays/LunarPhase
/usr/include/KF6/KHolidays/KHolidays/SunRiseSet
/usr/include/KF6/KHolidays/KHolidays/Zodiac
/usr/include/KF6/KHolidays/kholidays/astroseasons.h
/usr/include/KF6/KHolidays/kholidays/holiday.h
/usr/include/KF6/KHolidays/kholidays/holidayregion.h
/usr/include/KF6/KHolidays/kholidays/kholidays_export.h
/usr/include/KF6/KHolidays/kholidays/lunarphase.h
/usr/include/KF6/KHolidays/kholidays/sunriseset.h
/usr/include/KF6/KHolidays/kholidays/zodiac.h
/usr/include/KF6/KHolidays/kholidays_version.h
/usr/lib64/cmake/KF6Holidays/KF6HolidaysConfig.cmake
/usr/lib64/cmake/KF6Holidays/KF6HolidaysConfigVersion.cmake
/usr/lib64/cmake/KF6Holidays/KF6HolidaysTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF6Holidays/KF6HolidaysTargets.cmake
/usr/lib64/libKF6Holidays.so

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libKF6Holidays.so.6.5.0
/V3/usr/lib64/qt6/qml/org/kde/kholidays/libkholidaysdeclarativeplugin.so
/usr/lib64/libKF6Holidays.so.6
/usr/lib64/libKF6Holidays.so.6.5.0
/usr/lib64/qt6/qml/org/kde/kholidays/kde-qmlmodule.version
/usr/lib64/qt6/qml/org/kde/kholidays/kholidaysdeclarativeplugin.qmltypes
/usr/lib64/qt6/qml/org/kde/kholidays/libkholidaysdeclarativeplugin.so
/usr/lib64/qt6/qml/org/kde/kholidays/qmldir

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kholidays/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/kholidays/6091db0aead0d90182b93d3c0d09ba93d188f907
/usr/share/package-licenses/kholidays/680ed9349d3d12bd39ddd36e8c4bc6b1b0cb1c0e
/usr/share/package-licenses/kholidays/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
